### ISSUE TITLE
Implement full matrix test builds (Travis / Github Actions)

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/omc3#224]
It is time to test our package(s) on all supported python versions across major operating systems.

From personal experience:

- Travis builds are extremely slow under a big matrix as only 2 or 3 will run concurrently
- Travis' `macOS` VMs take a very long time to spin up (~10-15 min)
- Travis support for `Windows` is still experimental.
- Github Actions don't have these problems
- Github Actions "only" offers `macos-latest` and `windows-latest` for these systems.

I started setting up github actions in the `feature/github_actions` branch.
This was branched off from `bugs/219/madx_macros` as it should soon be merged into `master`, but did reset the `tfs-pandas` dependency to `>=1.0` in order for the install step to not fail

We're expecting to find bugs in the new builds, will gather findings in this issue.

Commits that were pushed previously without referencing this issue: 92bed47, 73a3cf3, 6474dba and 10cf7b0

**Comment by fsoubelet** [comment]
First finding: 3.8 builds seem to fail when using `pandas>=1.0`. Reverting to `pandas==0.25.*` solved it in the next builds (10cf7b0, see also the [github builds](https://github.com/pylhc/omc3/actions/runs/266491460) and [travis builds](https://travis-ci.com/github/pylhc/omc3/builds/185927206))

**Comment by fsoubelet** [comment]
(Only basic tests ran for these pushes btw)

**Comment by fsoubelet** [comment]
**Second finding:**

The following plotting tests fail on macOS machines (see [github build](https://github.com/pylhc/omc3/runs/1148148600?check_suite_focus=true)):

- `tests/unit/test_amplitude_detuning.py::test_ampdet_plot`
- `tests/unit/test_plot_optics_measurements.py::test_phase`
- `tests/unit/test_plot_optics_measurements.py::test_phase_delta`
- `tests/unit/test_plot_optics_measurements.py::test_rdt_0040`
- `tests/unit/test_plot_spectrum.py::test_basic_functionality`
- `tests/unit/test_plot_spectrum.py::test_combined_bpms_stem_plot`
- `tests/unit/test_plot_spectrum.py::test_no_tunes_in_files_plot`

I can confirm the same tests fail locally on my machine, on `macOS 10.15.6`.

These all fail with `AttributeError: 'NoneType' object has no attribute 'points_to_pixels'`. As @mihofer suggested, this is probably a backend thing. Maybe we should set a specific backend on the test files?

**Comment by fsoubelet** [comment]
Problem also for our time tools: https://pypi.org/project/pytz-deprecation-shim/

**Comment by fsoubelet** [comment]
Worth noting the `documentation` workflow is currently not good as it reproduces the `travis-sphinx` command and still needs to be modified

**Comment by fsoubelet** [comment]
The plotting tests failing on `macOS` machines is solved in commit 2e7cb3b (tests failed because of a typo that was fixed in commit c46c029).

The problem was indeed a backend / canvas issue, due to the use of `matplotlib.figure.Figure` instead of `matplotlib.pyplot.figure`. As `Figure` does not nicely set up a canvas for us (while `figure` does), the backend is also not properly setup and it's our job to do so.

I elected to simply command `matplotlib` to use a specific backend (chosen as the non-interactive `Agg`) in test files rather than changing code in the repo, as this issue only focuses on CI.

A SO post talking about the same phenomenon: https://stackoverflow.com/questions/17538235/unable-to-save-matplotlib-figure-figure-canvas-is-none

**Comment by fsoubelet** [comment]
As of commit d7ae2ef the `Basic Tests` workflow actually runs all tests so I can see everything works fine.
Will now be going back to allowing `pandas 1.x` and try to understand what happens.

**Comment by fsoubelet** [comment]
As suspected from previous builds' `DeprecationWarning`s, the issue on `Python 3.8` + `pandas 1.x` was that `pandas` stopped registering matplotlib converters automatically for datetime plotting.

The fix is to remember to manually `register_matplotlib_converters()` in `plot_bbq`, but also all plotting modules using time data in the future.

As of commit 48cc331, this is fixed and the full matrix tests pass.

**Comment by mihofer** [comment]
one small other thing, github action is limited to 2000 minutes per month for the free account .. do we have any estimate how many PR/ basic tests we can run before we run out of those?
bc since it kinda complements travis, i'd think we could only be using it every X days and for special PRs to check that macos and windows builds also work

**Comment by mihofer** [comment]
> 
> 
> one small other thing, github action is limited to 2000 minutes per month for the free account .. do we have any estimate how many PR/ basic tests we can run before we run out of those?
> bc since it kinda complements travis, i'd think we could only be using it every X days and for special PRs to check that macos and windows builds also work
> 
> or .. somebody sacrifices their office computer and we use it as self hosted runner ..

nvm, 2000 minutes only applies to private repos

**Comment by fsoubelet** [comment]
Failed ededb0d as I merged and resolved conflicts by accepting the state of test files from `master`, which removed the forcing of a proper backend for tests. 

Fixed in 1530061

**Comment by fsoubelet** [comment]
Also worth writing here that through in-person discussions we have elected to get rid of the Travis CI.
